require('plugins.lazy')
require('settings')
require('keymappings')
require('plugins.lualine')
require('plugins.nvim-treesitter')
require('plugins.lsp-settings')
require('plugins.minimal-plugins-conf')
